### ISSUE TITLE
API/CLI to know what changed in the commit

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#105]
Question from @Suor 

> Is there a way to know whether model were added or removed/deprecated in a particular commit or in a checked out commit?
Or better is it possible to list all such changes for a commit?

**Comment by aguschin** [comment]
> filter out model events from commits with no changes to a particular model

It would be great if we could have changes for each commit in commit index for `RepoIndexManager` from GTO. cc. @aguschin

_Originally posted by @amritghimire in https://github.com/iterative/studio/issues/3727#issuecomment-1149519488_

**Comment by aguschin** [comment]
We also had a discussion with @amritghimire about this, posting here for visibility:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/6797716/174250296-d00a0d05-6b7c-46fb-9946-e5c6b47dfcdd.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/6797716/174250375-e22f8a35-f533-4b20-aba5-652e8abafb8b.png">

**Comment by omesser** [comment]
@amritghimire  / @aguschin several things here:
1. structure - sounds like you're reinventing [jsonpatch](https://jsonpatch.com/). Please take a look if that works and we can just stick to jsonpatch semantics

2. In case of multiple parent commits the changes / diffs section will need to create multiple sets of changes, each relating to different parent
so maybe:
```json
{
   "changes": {
     "<commit-sha1>": { "patch": [<jsonpatch-op1>, <jsonpatch-op2>, ...] },
     "<commit-sha2>": { "patch": [<jsonpatch-op1>, <jsonpatch-op2>, ...] }
     ...
   }
}
```
