### ISSUE TITLE
`gto add` and `artifacts.yaml` arguments/fields

### ISSUE THREAD

**Issue by dberenbaum** [iterative/gto#122]
Some questions/feedback on `gto add` and `artifacts.yaml`:

My biggest question is whether the `gto add TYPE NAME PATH` really needs all 3 required arguments. It's a lot to remember and type to add an artifact, and it's not clear why all 3 are required and how each is useful. Related questions:

1. Why not make a `--type` option instead?
2. Should artifacts be defined by path or name? It's unclear if names are intended to be aliases for paths, or if names are the primary artifact identifiers, in which case it's unclear why paths are required. If paths aren't required, `--virtual` is probably not even necessary since external artifacts could be added without paths.
3. Why is the name listed both as a top-level key in `artifacts.yaml` and also under each key in the `name` field? Are both needed?

One smaller unrelated question:

4. Could tags be renamed to something else like labels to avoid confusion with git tags?

**Comment by jorgeorpinel** [comment]
Just found this. Interesting discussion

> I never seen git tags like path/to/something@v1.0.0. Finally, from technical perspective, git tags that contain slashes / may cause some issues

My related comment is that at least GTO tags should at least be grouped into `gto/alias@version` format. This could be useful for other systems to avoid clutter when displaying Git tags (hypothetically).
