### ISSUE TITLE
Allowing to promote to empty Stage

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#133]
If you promoted artifact version once, there is no way to get back to empty stage:
```
$ gto promote model prod
Created `model#prod-1` git tag
# now model in prod
```
Technically it's possible to allow to promote to special empty Stage:
```
$ gto promote model --empty-stage
Created `model#-2` git tag
```

I'm not sure about implemented this. User can have his own special stage called "none" or whatever. A con, to my mind is that having git tags like `model#-2` seem a bit awkward. CLI commands now will look like this:
```
$ gto promote model --empty-stage
$ gto which model --empty-stage
```
I think we need this --empty-stage because otherwise you can misinterpret what happens, e.g.
```
$ gto promote model  # I may just forgot I need to put STAGE arg - I do this myself regularly
$ gto which model  # I may want to see all stages here: like "stage1 -> v1; stage2 -> v2; ..."
```

Pros, on the other hand:
- I can imagine some users would want to promote version back to this "empty" stage

**Comment by dberenbaum** [comment]
I am a proponent of custom stages because I think ML deployments can become quite complex [progressive delivery](https://www.weave.works/blog/gitops-machine-learning-model-training) use cases, but I'm not sure we need to do much about it now besides keep it in mind for the future. I agree that focusing on default stages that make the basic benefits obvious seems more helpful for initial release.

**Comment by aguschin** [comment]
Considering your feedback about pre-defined stages, I see two options to add them:
1. adding `$ gto init` command that should create `gto.yaml` config file with a set of pre-defined stages.
2. have them as a default in GTO internals. So if you don't have `gto.yaml` at all, you'll get those 2 or 3 stages.

The difference is what happens by default. In the 1st case, if you skip `$ gto init`, you don't have any pre-defined stages, and you can create any. Let's say you register a first version of your model, run `$ gto show`, and see no stages.

But, with the 2nd option I can't see how one allow using any names for envs. Something like `allowedStages: any`? compare that to `allowedStages: ["dev", "prod"]`. We may need a separate option like `allowAnyStage: true`.

**Comment by aguschin** [comment]
@omesser @dberenbaum WDYT?
I'm leaning towards the first one and implementing pre-requisites for it as part of https://github.com/iterative/gto/issues/143

**Comment by aguschin** [comment]
> 1. adding `$ gto init` command that should create `gto.yaml` config file with a set of pre-defined stages.

Created an issue for this https://github.com/iterative/gto/issues/229

Closing this issue since we changed Stages mechanics and this discussion is not relevant any more
