### ISSUE TITLE
docs: consistent docstrings or self-doc code in `gto.api`

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/gto#137]
Either one could be enough API documentation for now.

_Originally posted by @jorgeorpinel in https://github.com/iterative/gto/pull/136#discussion_r853706339_

**Comment by jorgeorpinel** [comment]
Oops, didn't mean to self-assign 😅

**Comment by aguschin** [comment]
I think that was resolved. CLI commands have consistent docstrings now. Beside that we have README and that's all.
