### ISSUE TITLE
`show` to show stages from config only

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#143]
Right now `gto show` prints all stages it finds in repo. Adding `stage_allowed` to config doesn't change the behavior.

How it should work:
1. If you didn't specify `stage_allowed` in config, `gto show` shows all stages that exists in git tags.
2. If you specify `stage_allowed` in config, `gto show` shows only those stages.

Consequently, `gto stages` will work like this:
```shell
$ gto stages  # the same behavior as `gto show`
$ gto stages --allowed  # only those in config, empty output if None
$ gto stages --used  # all from git tags, empty output if None
```

**Comment by omesser** [comment]
my thoughts:
1. `stage_allowed` -> `allowed_stages` (or `stages` even?)
2.
```shell
$ gto stages  # the same behavior as `gto show`
$ gto stages --allowed  # only those in config, empty output if None
```
to
```shell
$ gto stages  # only those in config, all from labels if config key is missing (or empty?)
$ gto stages --all # ignore the config even if exists, show all stages from tags
```

**Comment by aguschin** [comment]
@omesser Thanks! What you described is just the same I think. So I guess my explanation above was not clear enough 😅 
So, it will work like this. Does it look like what you supposed it to be?

## Case 1 (existing config)
```yaml
# .gto
stage_allowed: [dev, prod]
```
git tags that exist: `model#staging`

```shell
$ gto stages
dev
prod
$ gto stages --allowed
dev
prod
$ gto stages --used
staging
```

## Case 2 (empty config)
```yaml
# .gto
```
git tags that exist: `model#staging`

```shell
$ gto stages
staging
$ gto stages --allowed
$ gto stages --used
staging
```

## Case 3 (config with empty stages)
```yaml
# .gto
stage_allowed: []
```
git tags that exist: `model#staging`

```shell
$ gto stages
$ gto stages --allowed
$ gto stages --used
staging
```

Not sure how to distinguish between [] and None (not defined) in CLI. But not sure we need that.

**Comment by aguschin** [comment]
> When outputting Yaml/Json it should be clear, right?

Yes, good solution! Thanks!

> A question - do we also need "--all" as I suggested above? Probably not 🤔. What if the user gives both --used and --allowed switches? Error?

Yes.
