### ISSUE TITLE
Check out interactive UI examples

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#151]
@mvshmakov, you've recommended to check out [`lazydocker`](https://github.com/jesseduffield/lazydocker) and few other packages. Could you please post references to them? Thanks!

**Comment by jellebouwman** [comment]
@aguschin I took a look at `lazygit` after our sync: https://github.com/jesseduffield/lazygit

**Comment by mvshmakov** [comment]
@aguschin, basically what I had in my mind is the following list:
* [lazygit](https://github.com/jesseduffield/lazygit)
* [lazydocker](https://github.com/jesseduffield/lazydocker)
* [gh-dash](https://github.com/dlvhdr/gh-dash)

All are the interesting examples of convenient TUI dashboards, but an important thing to know about them is that all of these packages are non-official (created by the community) and I haven't seen any official apps doing such kind of things ever.

**Comment by aguschin** [comment]
It was decided we don't need this in GTO, at least for now. Thank you for all the links, I'm closing the issue 👋
