### ISSUE TITLE
Incorrect version sorting

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#157]
Reported by @Suor and @amritghimire.
If you register `3.0.0`, then `2.5.2-bugfix`, then the latest will be `2.5.2-bugfix`:
https://github.com/iterative/gto/blob/e32504686e250609662b5698301edbb1e77c5c7e/gto/base.py#L76-L87

Related to #132

**Comment by omesser** [comment]
There are a bunch of (contradicting) ways to do this, using `distutils` (marked for deprecation), and setuptools as well has some parsing mechanism that will resolve to some *python-specific* versioning (see [PEP440](https://peps.python.org/pep-0440/))
None are actually semver :)

I suggest the element of least surprise and also being compliant with semver (language agnostic).
Something like using semver package -> with well defined/expected semver ordering, and non-semver compliant tags can be pushed to bottom and sorted using something which sorts "all" - like [natsort](https://pypi.org/project/natsort/)

**Comment by amritghimire** [comment]
@aguschin Can you create a publicly available key or compare function while you implement the version sorting in GTO?

**Comment by aguschin** [comment]
I'm implementing this right now and will ship the new release with this and #147 today. Do you need something beside that?

**Comment by amritghimire** [comment]
Thanks, That will be all for now. @aguschin

**Comment by aguschin** [comment]
closed by #161 
release 0.1.8 should happen in an hour, so you could try it out
@amritghimire, please note that GTO doesn't support sorting of SemVers with suffixes, e.g. `2.5.2-bugfix` yet. It will properly sort `x.y.z`, but not `x.y.z-suffix`. I plan to address it a bit later in #146
