### ISSUE TITLE
Design an initial logo for GTO

### ISSUE THREAD

**Issue by jellebouwman** [iterative/gto#159]
_(Originally posted in [Studio](https://github.com/iterative/studio) as https://github.com/iterative/studio/issues/3621)_

For MLEM models we have been using framework icons to communicate that
- the framework that was used to create the ML Model
- this model version is saved with MLEM

After some discussion, it might be good to have a visual indication of a GTO model in Studio to indicate
- this version is registered with GTO
- this version is not saved with MLEM

In Studio we can go ahead and use a very basic `G` sign for now, but this might be relevant for GTO from a branding perspective too.

**Comment by shcheklein** [comment]
I don't think it's relevant now.
