### ISSUE TITLE
Add a way to specify both author and committer for `gto.api.register()/promore()/annotate()`

### ISSUE THREAD

**Issue by Suor** [iterative/gto#171]
We need this so that author would be set to someone actually triggering the action and committer to out bot. 

**NOTE:** this might be tricky for tag creation. I didn't find a better way within `gitpython` than manipulating ENV vars.

**Comment by Suor** [comment]
The reason I am not a big fan of using this `environ()` solution from #173 is that theoretically might leak. Using context manager makes it quite reliable though, unless you use threads, which means if you do that inside `gto` then this will be non-threadsafe, as the whole `gto`. 

The better way is to limit env changes to a particular git command call or `git.cmd.Git()` instance:
```python
# Won't leak to other git commands, but if used carelessly might leak until `repo.git` is reused
repo.git.update_environment(GIT_COMMITTER_NAME=..., ...)
repo.git.tag(...) 

# Only used for a single call, the safest option with gitpython probably
repo.git.tag([...], env={"GIT_COMMITTER_NAME": ..., ...})
```

**Comment by aguschin** [comment]
Thanks for better alternatives, @Suor. Then I think I'm adding `tagger_name` and `tagger_email` arguments to `gto.api.register` and `gto.api.promote` the way you suggested.

At the same time, `gto.api.annotate` doesn't create git commit / git tag, so there is no way to specify author.
