### ISSUE TITLE
Multiple stages set to the same version

### ISSUE THREAD

**Issue by shortcipher3** [iterative/gto#179]
We have multiple pools of users of our models, an `alpha` pool, a `beta` pool, `production`, etc.  This seems like a natural fit for `gto` stages, however a model may be in both `alpha` and `beta` simultaneously.  How do I handle that with `gto`?  If I run:
`gto promote mymodel alpha`
followed by:
`gto promote mymodel beta`

`gto show` indicates the version only for `beta`.

**Comment by aguschin** [comment]
Good question, @shortcipher3! We've been considering replacing `Stages` with `Labels`, to make this work just like you described.

`Stages`, instead, work by assigning a single `stage` to the artifact version (single at any moment of time). So if promote `mymodel` to `beta`, it's considered to replace `alpha` (think about promotion to Stage like moving tasks on Kanban board). This is also how Stages in MLFlow MR work.

Regarding your workflow: do you need both mechanics (Stages and Labels), or Labels are enough?

**Comment by shortcipher3** [comment]
Makes sense. `Labels` are all I want for my current workflow.

**Comment by aguschin** [comment]
The Stages mechanics change in #218 should have fixed this. Thanks, @shortcipher3! Please leave feedback if you'll have some!
