### ISSUE TITLE
Errors after creating .gto config file

### ISSUE THREAD

**Issue by shortcipher3** [iterative/gto#181]
Was following along the README with the example repo and created a .gto config file with contents:
```
type_allowed: [model, dataset]
stage_allowed: [dev, stage, prod]
```
as described in the README.

However after creating the config file I'm getting errors when running gto commands.

```
# gto show
❌ Wrong config file '/Users/me/code/repos/model_registry/gto/gto_clone/.gto'
```

**Comment by aguschin** [comment]
Thanks, I'm fixing the readme. It should be
```
types: [model, dataset]
stages: [dev, stage, prod]```
