### ISSUE TITLE
Annotating `.dvc` files

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#185]
As @dberenbaum mentioned:
> It would be great if we can be flexible and support either the original model file or .dvc and treat them as the same.

Note that annotating `mymodel.h5` and `mymodel.h5.dvc` is different, and may have different consequences.

Currently, if you run
```shell
$ gto annotate mymodel --path mymodel.h5.dvc
```
you get annotated an artifact with this path. Then (for example) GTO<>MLEM integration won't work, since GTO will ask MLEM about model located in `mymodel.h5.dvc` and MLEM will expect there is `mymodel.h5.dvc.mlem` file, which is wrong.

We can either:
1. fix `--path mymodel.h5.dvc` to `--path mymodel.h5` automatically
2. issue warning ("hey, it's DVC file, probably you meant `mymodel.h5`)
3. understand internally that it's DVC file and it was intended to be `mymodel.h5` and we should ask MLEM about `mymodel.h5` here
4. do nothing

WDYT would be the better solution here? @dberenbaum

**Comment by dberenbaum** [comment]
@aguschin I think option 1 seems like the most straightforward. Do you see any complications to that approach?

**Comment by aguschin** [comment]
@dberenbaum 
It looks a bit unexpected to me, but I guess that's because I understand the way this works internally.
Can't imagine someone will want to register `mymodel.h5.dvc` though 🤔 

Couple of options:

1. Should GTO have some simple autocorrection logic that default extensions `mymodel.h5.dvc` and `mymodel.h5.mlem` corrected to just `mymodel.h5`? And have option to change this behavior in GTO config?

2. Or GTO should rely on DVC and MLEM enrichment mechanism to ask them what the right file is? E.g. you may have a MLEM file called `models/mymodel.mlem` though the actual binary is located under `mymodel.h5`. Don't know whether `.dvc` files could have this kind of indirection, but `.mlem` files can, so let's suppose there is also `mymodel.h5.dvc` nearby. Now when you annotate with `$ gto annotate model --path models/mymodel.mlem --exists` GTO checks that file exists and will annotate presumable the wrong file (`.mlem` one). What we can do is make GTO also ask DVC&MLEM to find enrichments for given path and return the correct file path - i.e. correct `models/mymodel.mlem` to `mymodel.h5` thanks to MLEM (DVC didn't returned anything cause DVC doesn't know about `models/mymodel.mlem`). This won't work if MLEM/DVC aren't installed though.

Also adding in @omesser for a feedback :)

**Comment by aguschin** [comment]
Ok! Thanks for coming back with the resolution. Closing this!
