### ISSUE TITLE
API call to check if the repo is a GTO repo

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#186]
There is no clear definition what is "a GTO repo", but I assume:
1. If there is a `.gto` config file - it's a GTO repo
2. If there is an `artifacts.yaml` file - it's a GTO repo
3. If there are some git tags that register/promote artifacts, it's GTO repo

Although all signals may have False Positives (e.g. you created some tags of GTO format with some other tool and didn't mean GTO; or you created `artifacts.yaml` without intention to use it with GTO), I think it's safe enough to expect it's a GTO repo and try to parse it accordingly (at least it's what GTO CLI&API will do).

cc @amritghimire

**Comment by shcheklein** [comment]
Why can't we assume that every repo is a GTO repo? ... some of them are empty for now, that's fine.
