### ISSUE TITLE
Improve `example-gto` repo

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#203]
In https://github.com/iterative/example-repos-dev/pull/110, example GTO repo is generated.

It lacks an example of downstream model usage. Currently, all model references are non-existing external / not-real internal models. We need to add the example of using actual ML model, or at least example of using the dummy model.

This will help both demo and checking that we have happy path implemented with GTO.

**Comment by aguschin** [comment]
cc @mike0sv

**Comment by mike0sv** [comment]
https://github.com/iterative/example-gto-mlem TAL

**Comment by aguschin** [comment]
Adapted your repo as a `mlem` branch for `example-gto` repo in https://github.com/iterative/example-repos-dev/pull/133
