### ISSUE TITLE
Fix `check-ref artifact@v1.0.0 --stage`

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#206]
Looks like it doesn't work now - `gto check-ref --repo https://github.com/iterative/example-gto churn@v3.0.0 --stage` just doesn't give any results 🤔

**Comment by aguschin** [comment]
Looks like it doesn't work now - `gto check-ref churn@v3.0.0 --stage` on `example-gto` just doesn't give any results 🤔

**Comment by tapadipti** [comment]
FWICT, this is expected. `gto check-ref` command is expected to check the provided ref (Git tag) and return its details. The Git tag `churn@v3.0.0` does not contain any details about the stage, so it cannot be expected to return details about the stage. If you try `gto check-ref --repo https://github.com/iterative/example-gto churn#prod#3 --stage`, you will get the stage as expected.

The command that does return all stages for a given artifact version is `gto show`. If you run `gto show --repo https://github.com/iterative/example-gto churn@v3.0.0`, you will see the assigned stages for this artifact version.
