### ISSUE TITLE
Artifact registry as remote entity

### ISSUE THREAD

**Issue by francesco086** [iterative/gto#220]
I am using GTO for my projects at work. I believe that GTO could be much more than what is now. For now I created some patch-scripts to do what I need, but I would be happy to contribute to make GTO more "powerful" if this is in line with iterative's vision. Here are my scripts:
https://gitlab.com/francesco-calcavecchia/git-repo-as-versioned-storage

**Comment by aguschin** [comment]
Thanks, @francesco086! Those are very interesting scripts!

From what I see, those fall into a few categories:

1. Running GTO commands against remote repos https://github.com/iterative/gto/issues/25
    - "read-only" commands like `which` - easier to implement
    - "r/w" commands - `register`, `promote` that require pushing a git tag - may be a bit trickier. Somehow relevant ticket about adding a `status` command https://github.com/iterative/gto/issues/115
  
2. `publishing` files in DVC repo (`git-dvc-remote-commit-and-push`). I think we need a ticket in the DVC repo for this. Doesn't require GTO.

3. `dvc-remote-get` should work with `$ dvc get` only. If you want to download exactly `"mymodel" in Stage "prod"` or `"mymodel" version "v0.0.1"`, you could combine GTO and DVC like this: `$ dvc get mymodel.pkl --rev $(gto which mymodel prod) -o mymodel` (this requires you to know the path to model binary and the name for it in GTO). If that doesn't solve your case, please add more details :). Relevant issue is #80 

Overall, please feel free to post more suggestions/ideas, create a ticket about `2.` in DVC repo to get DVC some suggestions on it, and contribute to any of this in GTO or DVC :) I believe everything here is in line with Iterative's vision but does not always in line with our capacity 😂

**Comment by francesco086** [comment]
Thanks @aguschin for the awesome work! It is very helpful, I will create a issue in the dvc repo for `2.`.

I am happy to contribute, I think I will start from the easy remote `gto which`. But only after my vacations :D
