### ISSUE TITLE
README.md not up to date in `v0.2.1`

### ISSUE THREAD

**Issue by tibor-mach** [iterative/gto#232]
I followed the [assigning stage](https://github.com/iterative/gto#assigning-a-stage-to-version) in getting started and in gto 0.2.1. the following does not work
```
gto assign awesome-model --version v0.0.1 --stage prod
```

 This is because `--stage` is no longer an option, but a required argument (without the option to use the keyword --stage):
![image](https://user-images.githubusercontent.com/56956998/187036537-aadc2bb4-732b-4e5c-ae66-d895f39b52b6.png)

So now, it has to be assigned like this

```
gto assign awesome-model prod --version v0.0.1
```

It might be nice to allow using the --stage keyword (even when it is a required argument), it makes for a more readable code (when used e.g. in CICD workflows).

**Comment by aguschin** [comment]
Thanks, didn't mean to change it now. I was looking to simplify commands, so if you have an idea how to simplify anything in CLI and make it more intuitive, please do a suggestion)
