### ISSUE TITLE
Feature request: `gto show --type`

### ISSUE THREAD

**Issue by tibor-mach** [iterative/gto#259]
If `gto` is used in a single repository to keep track of multiple artifact types (e.g. models and datasets), it would help greatly if `gto show` could be filtered by artifact type(s).

[Here](https://discord.com/channels/485586884165107732/1015962755611754577)'s a bit more discussion around that idea (mostly a justification for such a workflow) and related stuff.

**Comment by aguschin** [comment]
Closing since now index resides in DVC and GTO may not know artifact type.
