### ISSUE TITLE
gto register shows incorrect push command

### ISSUE THREAD

**Issue by igordertigor** [iterative/gto#302]
When registering a commit with `gto register`, I see a message similar to this:
```
Created git tag 'mymodel@v0.0.1' that registers version
To push the changes upstream, run:
    git push mymodel@v0.0.1
```
However, the git command is incorrect and should be `git push origin mymodel@v0.0.1` (or potentially something else depending on the desired repo).

I would submit a PR for this, but it seems that the relevant fix is already there in `gto/registry.py +487`. I'm using version 0.2.3 downloaded from pypi about 10 minutes ago.

**Comment by aguschin** [comment]
Yep, thanks! I'm releasing 0.2.4 (should have done it a while ago I guess). cc @francesco086
