### ISSUE TITLE
Make `example-gto` repo easy to understand without leaving it's GH page

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#303]
Let's suppose someone has been told that the [example-repo](https://github.com/iterative/example-gto) is a "Model Registry in Git" and opens that repo for the first time. Would be nice to have a catchy and to-the-point explanation of why it is a Model Registry. 
Some ideas:
- add `gto show` output to README
- add a screenshot from Studio to `example-gto` repo to README
- Add link to Studio "preview MR" would be also good to have.

**Comment by aguschin** [comment]
I've put together a quick example which can be enough for the start: https://github.com/aguschin/example-gto

It's in my own fork, so for now just experimenting, but I plan to move this to `iterative/example-gto`.

@shcheklein, WDYT?

**Comment by shcheklein** [comment]
It's a good start, but I think the idea with preview and video is really good. I would put something. Doesn't need to be polished, etc.

**Comment by aguschin** [comment]
Tried to simplify that even more.

**Comment by aguschin** [comment]
btw, @jorgeorpinel suggested another variant for the README https://github.com/iterative/example-gto/pull/14

WDYT?

**Comment by shcheklein** [comment]
This is too much of a simplification. We need to have a sentence or two about what it is, how it works (high level, can be a diagram), I still think video would be also beneficial ...

**Comment by jorgeorpinel** [comment]
Well the `main` branch was already shortenned even more, see https://github.com/aguschin/example-gto#readme .

I like this version by @aguschin's TBH, but it would hurt to explain a little more, or add a diagram as @shcheklein mentioned.

> My proposal: https://github.com/jorgeorpinel/example-gto/tree/patch-1#readme

> video would be also beneficial

Video for an example repo seems overkill though? 🤷🏼

**Comment by aguschin** [comment]
> Will we end up adding some more Installation info?

@jorgeorpinel, I think we don't need the installation info TBH. Let's redirect to Get started - it has hints about installation. My take that this README should:
1. Explain what is in front of the user (what is this GH repo)
2. Send a user to some page to learn more about this (to the Get Started).

Get started should have all other information about this, including venv creation + install (for some reason we removed that from GS, maybe we should add it back).

**Comment by aguschin** [comment]
added link to studio public MR in https://github.com/iterative/example-repos-dev/pull/250
closing for now.
