### ISSUE TITLE
View DVC metrics with GTO

### ISSUE THREAD

**Issue by mattangus** [iterative/gto#336]
Is there any way to show metrics for each model tagged with GTO?

**Comment by aguschin** [comment]
Hi @mattangus! Rn DVC metrics and GTO artifacts aren't connected, so there is no `gto` or `dvc` command that will do that. Can you please give some details and describe what are you trying to achieve? If you maybe have a CLI command example in mind, with input and output, that can help me get it :)

**Comment by mattangus** [comment]
Thanks for the reply! I would like to do something similar to:

```
$ gto show metrics
╒════════════════════════════╤══════════╤═══════════════╤═════════════╤═════════════════════╕
│ name                       │ latest   │ latest metric │ #production │ #production metric  │
╞════════════════════════════╪══════════╪═══════════════╪═════════════╪═════════════════════╡
│ my model                   │ v1.3.0   │ 0.4           │ v1.2.0      │ 0.38                │
╘════════════════════════════╧══════════╧═══════════════╧═════════════╧═════════════════════╛
```

Kind of combining `dvc metrics show` with `gto show`.
