### ISSUE TITLE
Story: cli command to get the reference to the current stage

### ISSUE THREAD

**Issue by francesco086** [iterative/gto#357]
## Summary / Background
I have an artifact registry built with git + dvc + gto.
In a pipeline, I would like to get the reference to the current prod stage of that registry, so that I can get the artifact I need.
The only way I found to achieve this is:
```sh
gto history --repo REPO_URL --json ARTIFACT_NAME | jq '[.[] | select(.stage == "prod") | {commit: .commit, version: (.version)}] | sort_by(.version) | .[-1].commit'
```
This is quite cumbersome. It would be more convenient to have a dedicated command.

## Scope

- user can use a command like
  ```sh
  gto get-ref --repo REPO_URL --stage prod ARTIFACT_NAME
  ```
  and obtain in return the git commit reference to the current prod stage (e.g. `975ab374971367996379396eb88991d893a461f2`).

## Assumptions

- Commit hash is all you need, no need for other references like tags.

## Open Questions

- Is there any another way to obtain the same in a simple manner?

**Comment by aguschin** [comment]
@francesco086, I think you're looking for:

```shell
$ gto show -r http://github.com/iterative/example-gto churn#prod --ref
churn@v3.0.0
```
or 
```shell
$ gto show -r http://github.com/iterative/example-gto churn@latest --ref
churn@v3.1.1
```

Am I correct?

> In a pipeline, I would like to get the reference to the current prod stage of that registry, so that I can get the artifact I need.

Curious to learn more details about the use case. Do you have a cron job in your repo that deploys daily/weekly? Or it is something else?

**Comment by aguschin** [comment]
Cool, thanks. Good to know how you use it!

**Comment by francesco086** [comment]
@aguschin in few month I think I will reach out you or Jennifer or whoever you think is best at iterative, perhaps it could be useful if I share what I have done ;)
