### ISSUE TITLE
Story: Bring back consistency between `--push` and `--commit` options and default behaviour with remote repos

### ISSUE THREAD

**Issue by francesco086** [iterative/gto#358]
## Summary / Background
Currently in the help descriptions one reads, for example
```
--push                         Push created tag automatically (experimental)
```
but if `--repo` is fed with a remote repo, the push is happening automatically (which makes sense). However, the description is not clear. Same with the `--commit` option.

It would be useful to update the help page to make it more understandable.

## Scope

These are the affected commands.
- `assign`
- `deprecate`
- `register`
- `annotate`
- `remove`

## Assumptions

- If repo is remote, then one surely wants to commit and push. If the repo is local with a remote, then it is optional.

## Open Questions

- Perhaps one could even get rid of the two options altogether, and make it happen for remote repos, and not for local ones.

**Comment by francesco086** [comment]
Happy to contribute once determined it makes sense ;)

I agree, an update in the documentation is sufficient. Perhaps I would suggest to explicitly mention that if specified repo is remote then push is automatically active. So, perhaps:
```
--push                         Push created git tag to `origin` (if provided remote repo with `--repo` this is automatic)
```

Regarding `annotate` and `remote`, no hard feeling from my side - this is why software is "soft" and not "hard"-ware :)

**Comment by aguschin** [comment]
Right, missed that part. Looks good to me! I'd also try to make it a bit more concise if possible, like:

```
--push                         Push created git tag to `origin` (done automatically for remote repo)
```

**Comment by francesco086** [comment]
Here the PR: https://github.com/iterative/gto/pull/363 (it took much longer to wait for all CI tests to finish running than to make the change 🤣 )

**Comment by aguschin** [comment]
I think this was fixed. Closing!
