### ISSUE TITLE
How to get `gto annotate` with gto `0.3.x`

### ISSUE THREAD

**Issue by rnoxy** [iterative/gto#365]
I know that `gto` is no longer using `artifacts.yaml`.
One should use `dvc` with `dvc.yaml`.

However, I do not know how to reproduce the previous `gto annotate` functionality with `dvc` CLI.

**Comment by aguschin** [comment]
Hi @rnoxy. As I showed in #364, there is a way to do the same with API. You can also annotate using `dvclive` or Studio https://dvc.org/doc/studio/user-guide/model-registry/add-a-model

If that doesn't help you, to better understand the priority for this, can you please explain your use case?

**Comment by aguschin** [comment]
I meant the code snippet [here](https://github.com/iterative/gto/issues/364#issuecomment-1566904171), please note it has an example of adding an annotation.
