### ISSUE TITLE
update GTO to be in line with iterative/py-template standards

### ISSUE THREAD

**Issue by pmrowla** [iterative/gto#400]
DVC officially, supports Python 3.8 through 3.11 but GTO CI is only run against 3.8 through 3.10 (GTO CI fails if you enable 3.11). As far as I can tell, the 3.11 failure is because GTO requires outdated pylint and mypy installations that are just broken on 3.11. The actual test suite passes in 3.11.

IMO there is a lot more work that needs to be done in GTO to bring it in line with current DVC and `iterative/py-template` standards, but for the time being I am leaving all of that alone (GTO codebase fails pylint/mypy checks after updating and enabling the py-template or DVC configurations for those tools)

Making GTO pass current mypy/pylint may also require updating other deps (and updating pydantic may require migrating from pydantic v1 to v2 - https://github.com/iterative/gto/pull/375)

_Originally posted by @pmrowla in https://github.com/iterative/gto/issues/378#issuecomment-1672866569_

**Comment by shcheklein** [comment]
I think we've updated pydantic, also it runs on 3.11. What else do we usually need to get it to py-template?

**Comment by pmrowla** [comment]
This can be closed, issues were all addressed in:
- https://github.com/iterative/gto/pull/408
- https://github.com/iterative/gto/pull/410
- https://github.com/iterative/gto/pull/413

**Comment by shcheklein** [comment]
Thanks, Peter. Do we want / need to upgrade it to py template?

**Comment by pmrowla** [comment]
There isn't really a straightforward way to retroactively apply a cookiecutter/cruft template on top of an existing git repo, so any major changes that are made in py-template in the future would need to be done manually in GTO.
