### ISSUE TITLE
Bug: `--bump-...` falgs don't work 

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/gto#407]
How to reproduce: 
``` 
gto register nn
gto register nn --bump-minor 
```
Unexpected error
```
❌ 'nn' is already registered in this commit with version 'v0.0.1'
```  
Expected behavior: GTP register a new version 'v0.0.2' 

Note: same error with `--bump-patch` and `--bump-major` as well

**Comment by shcheklein** [comment]
Does it happen since we don't allow multiple versions to be registered within a single commit / rev? Would you expect that to work, @mnrozhkov ?

**Comment by mnrozhkov** [comment]
Thank @shcheklein ! I totally missed the detail that 1 tag per commit.
