### ISSUE TITLE
`deprecate`: why depracate an entire model/artifact?

### ISSUE THREAD

**Issue by dberenbaum** [iterative/gto#430]
It's unclear to me the value of deprecating an entire model/artifact. Why is it not enough to unassign a stage or archive the git repo? I get confused with what this is supposed to do in gto and studio. Is there a known workflow where it is helpful/needed?

**Comment by shcheklein** [comment]
It disappears from the MR then. If you just unassign it you can still see it. You can't archive the whole if this is a monorepo, or you have an older model in your history that you don't want to see anymore.
