### ISSUE TITLE
Field naming - Datetime fields consistency

### ISSUE THREAD

**Issue by omesser** [iterative/gto#67]
⚠️ This is nit-picky ⚠️  😅 

Currently there are: `creation_date` + `unregistered_date` fields in the same place.

1. Those are _datetimes_ (so not `date`)
2. unregister[ed] -> deregister[ed] - my reasoning is [this](https://english.stackexchange.com/a/40095) - removing existing registration vs something was never registered before (unregistered)
3. if using `creat**ion** date` why not `deregistration` (as opposed to `deregistered`) (noun vs past verb)

This is a matter of style, preference and consistency with other tools (I don't know how it's done in dvc / studio / mlem / others) - but IMO a good convention for those would be `created_at`, `updated_at`, etc, so here: `registered_at`, `deregistered_at`
However, again - I don't know if this is consistent across our tools (mlem, dvc), if not, it's an inferior suggestion to something consistent

**Comment by aguschin** [comment]
There is `created_at` now. Others are not needed in the current implementation. Closing :)
