### ISSUE TITLE
Register pre-gto model versions

### ISSUE THREAD

**Issue by dberenbaum** [iterative/gto#77]
I may start using gto after already having a bunch of artifacts from previous commits that I want to register. There's no way that I can tell to register these older artifact versions since I haven't added them to `artifacts.yaml` in those commits (`artifacts.yaml` may not even exist).

More generally, should the metadata be read from the registered commit or from the current/latest commit?

**Comment by aguschin** [comment]
Ok, again, this is not possible with the current approach. Closing the issue.
