### ISSUE TITLE
GTO for large repos

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#88]
A question by @dberenbaum

> Since GTO may be especially useful for large repos:
    - Do you anticipate any problems using submodules, sparse checkout, etc.?
    - Will tags get too noisy?

Didn't think about submodules, sparse checkouts, etc yet.
As for noisy tags, the biggest number of tags I've seen so far exists in https://github.com/jupyterlab/jupyterlab
I've seen a dozen of repos with over than 5 tags, so people use that, not that often though.

Another problem for such number of tags/commits could be the speed. I've tried to parse git tags in Jupyterlab repo, and it seems to work quite fast. But current GTO architecture requires to read `artifacts.yaml` from each commit. I didn't try to do something like this. This should be next step to check how slow it's going to be.

**Comment by aguschin** [comment]
I recall running some experiments to optimize this, but the main problem was `git tags` (or alternatives) running to slow. Maybe after moving to scmrepo this actually works faster.

**Comment by shcheklein** [comment]
Closing this, we moved to scmrepo and to dvc.yaml. Let's hit the scale issue first here.
